🔄 ci: use `ubuntu-latest` runners for tests
For some reason I started getting this error in Actions:

```
$ bun run lint:oxc && bun run lint:spell
$ oxlint

thread 'tokio-rt-worker' (381) panicked at crates/oxc_allocator/src/pool/fixed_size.rs:112:67:
called `Result::unwrap()` on an `Err` value: ()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: script "lint:oxc" was terminated by signal SIGABRT (Abort)
/usr/bin/bash: line 1:   376 Aborted                 bun run lint:oxc
error: script "lint" exited with code 134
Error: Process completed with exit code 134.
```

I assume this is due to a lack of RAM in the slim runner, we will need to create an issue in oxc to further resolve the problem